services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: vector
      POSTGRES_PASSWORD: vectorpass
      POSTGRES_DB: vectordb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  vector:
    image: 	timberio/vector:latest-debian
    depends_on:
      - postgres
    volumes:
      - ./vector/vector.yaml:/etc/vector/vector.yaml:ro
    command: ["-c", "/etc/vector/vector.yaml"]
    ports:
      - "8686:8686"   # Vector admin UI
      - "514:514/udp" # Syslog UDP
      - "514:514/tcp" # Syslog TCP

volumes:
  pgdata: